graph LR
  N0_enemyAI["js/components/combat/enemyAI.js"] --> N13_component["js/core/component.js"]
  N0_enemyAI["js/components/combat/enemyAI.js"] --> N12_transform["js/components/transform.js"]
  N0_enemyAI["js/components/combat/enemyAI.js"] --> N1_healthComponent["js/components/combat/healthComponent.js"]
  N1_healthComponent["js/components/combat/healthComponent.js"] --> N13_component["js/core/component.js"]
  N2_mineable["js/components/mining/mineable.js"] --> N13_component["js/core/component.js"]
  N3_rigidbody["js/components/physics/rigidbody.js"] --> N13_component["js/core/component.js"]
  N4_mesh["js/components/rendering/mesh.js"] --> N13_component["js/core/component.js"]
  N5_trail["js/components/rendering/trail.js"] --> N13_component["js/core/component.js"]
  N6_cargo["js/components/spaceship/cargo.js"] --> N13_component["js/core/component.js"]
  N7_deployableLaser["js/components/spaceship/deployableLaser.js"] --> N13_component["js/core/component.js"]
  N8_miningLaser["js/components/spaceship/miningLaser.js"] --> N13_component["js/core/component.js"]
  N9_pickupable["js/components/spaceship/pickupable.js"] --> N13_component["js/core/component.js"]
  N10_shipState["js/components/spaceship/shipState.js"] --> N13_component["js/core/component.js"]
  N11_thruster["js/components/spaceship/thruster.js"] --> N13_component["js/core/component.js"]
  N12_transform["js/components/transform.js"] --> N13_component["js/core/component.js"]
  N17_entityManager["js/core/entityManager.js"] --> N15_entity["js/core/entity.js"]
  N19_messageBus["js/core/messageBus.js"] --> N18_events["js/core/events.js"]
  N24_world["js/core/world.js"] --> N17_entityManager["js/core/entityManager.js"]
  N24_world["js/core/world.js"] --> N23_systemManager["js/core/systemManager.js"]
  N24_world["js/core/world.js"] --> N19_messageBus["js/core/messageBus.js"]
  N24_world["js/core/world.js"] --> N21_SpatialHash["js/core/spatial/SpatialHash.js"]
  N24_world["js/core/world.js"] --> N16_EntityIndex["js/core/EntityIndex.js"]
  N25_spaceship["js/entities/spaceship.js"] --> N12_transform["js/components/transform.js"]
  N25_spaceship["js/entities/spaceship.js"] --> N3_rigidbody["js/components/physics/rigidbody.js"]
  N25_spaceship["js/entities/spaceship.js"] --> N4_mesh["js/components/rendering/mesh.js"]
  N25_spaceship["js/entities/spaceship.js"] --> N11_thruster["js/components/spaceship/thruster.js"]
  N25_spaceship["js/entities/spaceship.js"] --> N8_miningLaser["js/components/spaceship/miningLaser.js"]
  N25_spaceship["js/entities/spaceship.js"] --> N6_cargo["js/components/spaceship/cargo.js"]
  N28_diagnostics["js/main/diagnostics.js"] --> N80_perfOverlay["js/modules/debug/perfOverlay.js"]
  N30_gameInitializer["js/main/gameInitializer.js"] --> N156_renderer["js/modules/renderer.js"]
  N30_gameInitializer["js/main/gameInitializer.js"] --> N164_spaceship["js/modules/spaceship.js"]
  N30_gameInitializer["js/main/gameInitializer.js"] --> N135_physics["js/modules/physics.js"]
  N30_gameInitializer["js/main/gameInitializer.js"] --> N120_environment["js/modules/environment.js"]
  N30_gameInitializer["js/main/gameInitializer.js"] --> N79_controls["js/modules/controls.js"]
  N30_gameInitializer["js/main/gameInitializer.js"] --> N232_ui["js/modules/ui.js"]
  N30_gameInitializer["js/main/gameInitializer.js"] --> N38_audio["js/modules/audio/audio.js"]
  N33_globals["js/main/globals.js"] --> N19_messageBus["js/core/messageBus.js"]
  N33_globals["js/main/globals.js"] --> N137_PoolRegistry["js/modules/pooling/PoolRegistry.js"]
  N36_startupSequence["js/main/startupSequence.js"] --> N134_introSequence["js/modules/introSequence.js"]
  N37_main["js/main.js"] --> N56_combat["js/modules/combat.js"]
  N37_main["js/main.js"] --> N33_globals["js/main/globals.js"]
  N37_main["js/main.js"] --> N36_startupSequence["js/main/startupSequence.js"]
  N37_main["js/main.js"] --> N32_gameLoop["js/main/gameLoop.js"]
  N37_main["js/main.js"] --> N28_diagnostics["js/main/diagnostics.js"]
  N37_main["js/main.js"] --> N30_gameInitializer["js/main/gameInitializer.js"]
  N37_main["js/main.js"] --> N35_objectPools["js/main/objectPools.js"]
  N37_main["js/main.js"] --> N29_difficultyManager["js/main/difficultyManager.js"]
  N37_main["js/main.js"] --> N34_hordeMode["js/main/hordeMode.js"]
  N37_main["js/main.js"] --> N26_audioUpdater["js/main/audioUpdater.js"]
  N37_main["js/main.js"] --> N31_gameLifecycle["js/main/gameLifecycle.js"]
  N38_audio["js/modules/audio/audio.js"] --> N39_context["js/modules/audio/core/context.js"]
  N38_audio["js/modules/audio/audio.js"] --> N40_loader["js/modules/audio/core/loader.js"]
  N38_audio["js/modules/audio/audio.js"] --> N44_playlist["js/modules/audio/music/playlist.js"]
  N38_audio["js/modules/audio/audio.js"] --> N43_player["js/modules/audio/music/player.js"]
  N38_audio["js/modules/audio/audio.js"] --> N41_soundPlayer["js/modules/audio/effects/soundPlayer.js"]
  N38_audio["js/modules/audio/audio.js"] --> N42_enabler["js/modules/audio/mobile/enabler.js"]
  N40_loader["js/modules/audio/core/loader.js"] --> N272_pathUtils["js/utils/pathUtils.js"]
  N44_playlist["js/modules/audio/music/playlist.js"] --> N272_pathUtils["js/utils/pathUtils.js"]
  N52_effects["js/modules/combat/effects.js"] --> N48_explosionEffects["js/modules/combat/effects/explosionEffects.js"]
  N52_effects["js/modules/combat/effects.js"] --> N50_materialManager["js/modules/combat/effects/materialManager.js"]
  N52_effects["js/modules/combat/effects.js"] --> N49_geometryManager["js/modules/combat/effects/geometryManager.js"]
  N52_effects["js/modules/combat/effects.js"] --> N51_projectileEffects["js/modules/combat/effects/projectileEffects.js"]
  N54_registerSystems["js/modules/combat/registerSystems.js"] --> N234_combatSystem["js/systems/combat/combatSystem.js"]
  N54_registerSystems["js/modules/combat/registerSystems.js"] --> N243_enemySystem["js/systems/combat/enemySystem.js"]
  N54_registerSystems["js/modules/combat/registerSystems.js"] --> N265_renderSystem["js/systems/rendering/renderSystem.js"]
  N54_registerSystems["js/modules/combat/registerSystems.js"] --> N262_collisionSystem["js/systems/physics/collisionSystem.js"]
  N54_registerSystems["js/modules/combat/registerSystems.js"] --> N267_visualEffectsSystem["js/systems/rendering/visualEffectsSystem.js"]
  N54_registerSystems["js/modules/combat/registerSystems.js"] --> N266_trailSystem["js/systems/rendering/trailSystem.js"]
  N54_registerSystems["js/modules/combat/registerSystems.js"] --> N269_deployableLaserSystem["js/systems/weapons/deployableLaserSystem.js"]
  N54_registerSystems["js/modules/combat/registerSystems.js"] --> N253_deploymentSystem["js/systems/deployables/deploymentSystem.js"]
  N54_registerSystems["js/modules/combat/registerSystems.js"] --> N255_explosionHandler["js/systems/effects/explosionHandler.js"]
  N55_worldSetup["js/modules/combat/worldSetup.js"] --> N24_world["js/core/world.js"]
  N56_combat["js/modules/combat.js"] --> N55_worldSetup["js/modules/combat/worldSetup.js"]
  N56_combat["js/modules/combat.js"] --> N54_registerSystems["js/modules/combat/registerSystems.js"]
  N56_combat["js/modules/combat.js"] --> N53_events["js/modules/combat/events.js"]
  N56_combat["js/modules/combat.js"] --> N52_effects["js/modules/combat/effects.js"]
  N56_combat["js/modules/combat.js"] --> N45_aiAndSpawners["js/modules/combat/aiAndSpawners.js"]
  N56_combat["js/modules/combat.js"] --> N46_combatLogic["js/modules/combat/combatLogic.js"]
  N56_combat["js/modules/combat.js"] --> N138_ProjectilePoolManager["js/modules/pooling/ProjectilePoolManager.js"]
  N60_dockingSystem["js/modules/controls/dockingSystem.js"] --> N58_proximityDetector["js/modules/controls/docking/proximityDetector.js"]
  N60_dockingSystem["js/modules/controls/dockingSystem.js"] --> N57_dockingLogic["js/modules/controls/docking/dockingLogic.js"]
  N60_dockingSystem["js/modules/controls/dockingSystem.js"] --> N59_uiIntegration["js/modules/controls/docking/uiIntegration.js"]
  N68_miningSystem["js/modules/controls/miningSystem.js"] --> N63_laserControl["js/modules/controls/mining/laserControl.js"]
  N68_miningSystem["js/modules/controls/miningSystem.js"] --> N65_targetValidation["js/modules/controls/mining/targetValidation.js"]
  N68_miningSystem["js/modules/controls/miningSystem.js"] --> N64_resourceExtraction["js/modules/controls/mining/resourceExtraction.js"]
  N68_miningSystem["js/modules/controls/miningSystem.js"] --> N66_uiUpdates["js/modules/controls/mining/uiUpdates.js"]
  N68_miningSystem["js/modules/controls/miningSystem.js"] --> N67_visualEffects["js/modules/controls/mining/visualEffects.js"]
  N75_touchControls["js/modules/controls/touch/touchControls.js"] --> N77_joystickZones["js/modules/controls/touch/ui/joystickZones.js"]
  N75_touchControls["js/modules/controls/touch/touchControls.js"] --> N76_actionButtons["js/modules/controls/touch/ui/actionButtons.js"]
  N75_touchControls["js/modules/controls/touch/touchControls.js"] --> N74_joystickHandler["js/modules/controls/touch/input/joystickHandler.js"]
  N75_touchControls["js/modules/controls/touch/touchControls.js"] --> N73_gestureDetector["js/modules/controls/touch/input/gestureDetector.js"]
  N75_touchControls["js/modules/controls/touch/touchControls.js"] --> N70_miningHandler["js/modules/controls/touch/actions/miningHandler.js"]
  N75_touchControls["js/modules/controls/touch/touchControls.js"] --> N72_weaponHandler["js/modules/controls/touch/actions/weaponHandler.js"]
  N75_touchControls["js/modules/controls/touch/touchControls.js"] --> N71_systemActions["js/modules/controls/touch/actions/systemActions.js"]
  N78_touchControls["js/modules/controls/touchControls.js"] --> N75_touchControls["js/modules/controls/touch/touchControls.js"]
  N79_controls["js/modules/controls.js"] --> N62_inputHandler["js/modules/controls/inputHandler.js"]
  N79_controls["js/modules/controls.js"] --> N61_gamepadHandler["js/modules/controls/gamepadHandler.js"]
  N79_controls["js/modules/controls.js"] --> N68_miningSystem["js/modules/controls/miningSystem.js"]
  N79_controls["js/modules/controls.js"] --> N69_targetingSystem["js/modules/controls/targetingSystem.js"]
  N79_controls["js/modules/controls.js"] --> N60_dockingSystem["js/modules/controls/dockingSystem.js"]
  N79_controls["js/modules/controls.js"] --> N78_touchControls["js/modules/controls/touchControls.js"]
  N79_controls["js/modules/controls.js"] --> N271_mobileDetector["js/utils/mobileDetector.js"]
  N81_anomalyRegistry["js/modules/environment/anomalies/anomalyRegistry.js"] --> N86_vortex["js/modules/environment/anomalies/vortex.js"]
  N81_anomalyRegistry["js/modules/environment/anomalies/anomalyRegistry.js"] --> N82_crystalCluster["js/modules/environment/anomalies/crystalCluster.js"]
  N81_anomalyRegistry["js/modules/environment/anomalies/anomalyRegistry.js"] --> N84_nebulaNexus["js/modules/environment/anomalies/nebulaNexus.js"]
  N81_anomalyRegistry["js/modules/environment/anomalies/anomalyRegistry.js"] --> N85_quantumFlux["js/modules/environment/anomalies/quantumFlux.js"]
  N81_anomalyRegistry["js/modules/environment/anomalies/anomalyRegistry.js"] --> N83_darkMatter["js/modules/environment/anomalies/darkMatter.js"]
  N89_sceneInitializer["js/modules/environment/core/sceneInitializer.js"] --> N109_skybox["js/modules/environment/skybox.js"]
  N89_sceneInitializer["js/modules/environment/core/sceneInitializer.js"] --> N117_sun["js/modules/environment/sun.js"]
  N89_sceneInitializer["js/modules/environment/core/sceneInitializer.js"] --> N107_planets["js/modules/environment/planets.js"]
  N89_sceneInitializer["js/modules/environment/core/sceneInitializer.js"] --> N112_stargate["js/modules/environment/stargate.js"]
  N89_sceneInitializer["js/modules/environment/core/sceneInitializer.js"] --> N113_starSystemGenerator["js/modules/environment/starSystemGenerator.js"]
  N91_starDreadnought["js/modules/environment/dreadnought/starDreadnought.js"] --> N93_hull["js/modules/environment/dreadnought/structure/hull.js"]
  N91_starDreadnought["js/modules/environment/dreadnought/starDreadnought.js"] --> N92_bridge["js/modules/environment/dreadnought/structure/bridge.js"]
  N91_starDreadnought["js/modules/environment/dreadnought/starDreadnought.js"] --> N94_engines["js/modules/environment/dreadnought/systems/engines.js"]
  N91_starDreadnought["js/modules/environment/dreadnought/starDreadnought.js"] --> N95_weapons["js/modules/environment/dreadnought/systems/weapons.js"]
  N91_starDreadnought["js/modules/environment/dreadnought/starDreadnought.js"] --> N96_beam["js/modules/environment/dreadnought/teleporter/beam.js"]
  N91_starDreadnought["js/modules/environment/dreadnought/starDreadnought.js"] --> N98_particles["js/modules/environment/dreadnought/teleporter/particles.js"]
  N91_starDreadnought["js/modules/environment/dreadnought/starDreadnought.js"] --> N97_controller["js/modules/environment/dreadnought/teleporter/controller.js"]
  N97_controller["js/modules/environment/dreadnought/teleporter/controller.js"] --> N98_particles["js/modules/environment/dreadnought/teleporter/particles.js"]
  N100_systemFactory["js/modules/environment/generator/systemFactory.js"] --> N99_systemConfig["js/modules/environment/generator/systemConfig.js"]
  N100_systemFactory["js/modules/environment/generator/systemFactory.js"] --> N101_systemNames["js/modules/environment/generator/systemNames.js"]
  N100_systemFactory["js/modules/environment/generator/systemFactory.js"] --> N102_systemUtils["js/modules/environment/generator/systemUtils.js"]
  N102_systemUtils["js/modules/environment/generator/systemUtils.js"] --> N99_systemConfig["js/modules/environment/generator/systemConfig.js"]
  N103_planetFactory["js/modules/environment/planets/planetFactory.js"] --> N105_planetMaterials["js/modules/environment/planets/planetMaterials.js"]
  N105_planetMaterials["js/modules/environment/planets/planetMaterials.js"] --> N106_planetTextures["js/modules/environment/planets/planetTextures.js"]
  N107_planets["js/modules/environment/planets.js"] --> N104_planetGenerator["js/modules/environment/planets/planetGenerator.js"]
  N107_planets["js/modules/environment/planets.js"] --> N103_planetFactory["js/modules/environment/planets/planetFactory.js"]
  N108_portalRim["js/modules/environment/portalRim.js"] --> N18_events["js/core/events.js"]
  N110_spaceAnomalies["js/modules/environment/spaceAnomalies.js"] --> N81_anomalyRegistry["js/modules/environment/anomalies/anomalyRegistry.js"]
  N113_starSystemGenerator["js/modules/environment/starSystemGenerator.js"] --> N100_systemFactory["js/modules/environment/generator/systemFactory.js"]
  N113_starSystemGenerator["js/modules/environment/starSystemGenerator.js"] --> N102_systemUtils["js/modules/environment/generator/systemUtils.js"]
  N117_sun["js/modules/environment/sun.js"] --> N116_sunShaders["js/modules/environment/sun/sunShaders.js"]
  N117_sun["js/modules/environment/sun.js"] --> N114_sunFlares["js/modules/environment/sun/sunFlares.js"]
  N117_sun["js/modules/environment/sun.js"] --> N115_sunLighting["js/modules/environment/sun/sunLighting.js"]
  N120_environment["js/modules/environment.js"] --> N89_sceneInitializer["js/modules/environment/core/sceneInitializer.js"]
  N120_environment["js/modules/environment.js"] --> N88_regionManager["js/modules/environment/core/regionManager.js"]
  N120_environment["js/modules/environment.js"] --> N90_systemTransitionManager["js/modules/environment/core/systemTransitionManager.js"]
  N120_environment["js/modules/environment.js"] --> N87_asteroidBelt["js/modules/environment/asteroidBelt.js"]
  N120_environment["js/modules/environment.js"] --> N118_systemTransition["js/modules/environment/systemTransition.js"]
  N120_environment["js/modules/environment.js"] --> N218_customSystemCreator["js/modules/ui/customSystemCreator.js"]
  N120_environment["js/modules/environment.js"] --> N119_vibeVersePortals["js/modules/environment/vibeVersePortals.js"]
  N120_environment["js/modules/environment.js"] --> N110_spaceAnomalies["js/modules/environment/spaceAnomalies.js"]
  N123_initialization["js/modules/game/initialization.js"] --> N156_renderer["js/modules/renderer.js"]
  N123_initialization["js/modules/game/initialization.js"] --> N164_spaceship["js/modules/spaceship.js"]
  N123_initialization["js/modules/game/initialization.js"] --> N135_physics["js/modules/physics.js"]
  N123_initialization["js/modules/game/initialization.js"] --> N120_environment["js/modules/environment.js"]
  N123_initialization["js/modules/game/initialization.js"] --> N79_controls["js/modules/controls.js"]
  N123_initialization["js/modules/game/initialization.js"] --> N232_ui["js/modules/ui.js"]
  N123_initialization["js/modules/game/initialization.js"] --> N47_combatManager["js/modules/combat/combatManager.js"]
  N123_initialization["js/modules/game/initialization.js"] --> N56_combat["js/modules/combat.js"]
  N123_initialization["js/modules/game/initialization.js"] --> N38_audio["js/modules/audio/audio.js"]
  N123_initialization["js/modules/game/initialization.js"] --> N19_messageBus["js/core/messageBus.js"]
  N127_game["js/modules/game.js"] --> N123_initialization["js/modules/game/initialization.js"]
  N127_game["js/modules/game.js"] --> N125_stateManager["js/modules/game/stateManager.js"]
  N127_game["js/modules/game.js"] --> N126_systemCoordinator["js/modules/game/systemCoordinator.js"]
  N127_game["js/modules/game.js"] --> N124_lifecycle["js/modules/game/lifecycle.js"]
  N127_game["js/modules/game.js"] --> N121_eventHandlers["js/modules/game/eventHandlers.js"]
  N127_game["js/modules/game.js"] --> N122_helpers["js/modules/game/helpers.js"]
  N130_dialogueManager["js/modules/intro/audio/dialogueManager.js"] --> N272_pathUtils["js/utils/pathUtils.js"]
  N133_dialogueSystem["js/modules/intro/ui/dialogueSystem.js"] --> N130_dialogueManager["js/modules/intro/audio/dialogueManager.js"]
  N134_introSequence["js/modules/introSequence.js"] --> N111_starDreadnought["js/modules/environment/starDreadnought.js"]
  N134_introSequence["js/modules/introSequence.js"] --> N131_soundEffects["js/modules/intro/audio/soundEffects.js"]
  N134_introSequence["js/modules/introSequence.js"] --> N130_dialogueManager["js/modules/intro/audio/dialogueManager.js"]
  N134_introSequence["js/modules/introSequence.js"] --> N132_portalEffect["js/modules/intro/effects/portalEffect.js"]
  N134_introSequence["js/modules/introSequence.js"] --> N133_dialogueSystem["js/modules/intro/ui/dialogueSystem.js"]
  N134_introSequence["js/modules/introSequence.js"] --> N128_arrivalPhase["js/modules/intro/animation/arrivalPhase.js"]
  N134_introSequence["js/modules/introSequence.js"] --> N129_departurePhase["js/modules/intro/animation/departurePhase.js"]
  N138_ProjectilePoolManager["js/modules/pooling/ProjectilePoolManager.js"] --> N147_laser["js/modules/pooling/projectiles/types/laser.js"]
  N138_ProjectilePoolManager["js/modules/pooling/ProjectilePoolManager.js"] --> N148_missile["js/modules/pooling/projectiles/types/missile.js"]
  N138_ProjectilePoolManager["js/modules/pooling/ProjectilePoolManager.js"] --> N149_plasma["js/modules/pooling/projectiles/types/plasma.js"]
  N138_ProjectilePoolManager["js/modules/pooling/ProjectilePoolManager.js"] --> N146_bullet["js/modules/pooling/projectiles/types/bullet.js"]
  N138_ProjectilePoolManager["js/modules/pooling/ProjectilePoolManager.js"] --> N145_trails["js/modules/pooling/projectiles/effects/trails.js"]
  N138_ProjectilePoolManager["js/modules/pooling/ProjectilePoolManager.js"] --> N143_impacts["js/modules/pooling/projectiles/effects/impacts.js"]
  N138_ProjectilePoolManager["js/modules/pooling/ProjectilePoolManager.js"] --> N144_muzzleFlash["js/modules/pooling/projectiles/effects/muzzleFlash.js"]
  N138_ProjectilePoolManager["js/modules/pooling/ProjectilePoolManager.js"] --> N136_ObjectPool["js/modules/pooling/ObjectPool.js"]
  N143_impacts["js/modules/pooling/projectiles/effects/impacts.js"] --> N136_ObjectPool["js/modules/pooling/ObjectPool.js"]
  N143_impacts["js/modules/pooling/projectiles/effects/impacts.js"] --> N140_explosionFactory["js/modules/pooling/projectiles/effects/impacts/explosionFactory.js"]
  N143_impacts["js/modules/pooling/projectiles/effects/impacts.js"] --> N142_sparkFactory["js/modules/pooling/projectiles/effects/impacts/sparkFactory.js"]
  N143_impacts["js/modules/pooling/projectiles/effects/impacts.js"] --> N139_debrisFactory["js/modules/pooling/projectiles/effects/impacts/debrisFactory.js"]
  N143_impacts["js/modules/pooling/projectiles/effects/impacts.js"] --> N141_impactTypeHandler["js/modules/pooling/projectiles/effects/impacts/impactTypeHandler.js"]
  N144_muzzleFlash["js/modules/pooling/projectiles/effects/muzzleFlash.js"] --> N136_ObjectPool["js/modules/pooling/ObjectPool.js"]
  N145_trails["js/modules/pooling/projectiles/effects/trails.js"] --> N136_ObjectPool["js/modules/pooling/ObjectPool.js"]
  N146_bullet["js/modules/pooling/projectiles/types/bullet.js"] --> N136_ObjectPool["js/modules/pooling/ObjectPool.js"]
  N147_laser["js/modules/pooling/projectiles/types/laser.js"] --> N136_ObjectPool["js/modules/pooling/ObjectPool.js"]
  N148_missile["js/modules/pooling/projectiles/types/missile.js"] --> N136_ObjectPool["js/modules/pooling/ObjectPool.js"]
  N149_plasma["js/modules/pooling/projectiles/types/plasma.js"] --> N136_ObjectPool["js/modules/pooling/ObjectPool.js"]
  N152_post["js/modules/renderer/post.js"] --> N154_shaders["js/modules/renderer/shaders.js"]
  N156_renderer["js/modules/renderer.js"] --> N151_lighting["js/modules/renderer/lighting.js"]
  N156_renderer["js/modules/renderer.js"] --> N152_post["js/modules/renderer/post.js"]
  N156_renderer["js/modules/renderer.js"] --> N153_sceneApi["js/modules/renderer/sceneApi.js"]
  N156_renderer["js/modules/renderer.js"] --> N150_helpers["js/modules/renderer/helpers.js"]
  N156_renderer["js/modules/renderer.js"] --> N155_volumetricLighting["js/modules/renderer/volumetricLighting.js"]
  N159_spaceship["js/modules/spaceship/spaceship.js"] --> N165_trail["js/modules/trail.js"]
  N159_spaceship["js/modules/spaceship/spaceship.js"] --> N158_shipModel["js/modules/spaceship/model/shipModel.js"]
  N159_spaceship["js/modules/spaceship/spaceship.js"] --> N163_upgrades["js/modules/spaceship/systems/upgrades.js"]
  N159_spaceship["js/modules/spaceship/spaceship.js"] --> N161_docking["js/modules/spaceship/systems/docking.js"]
  N159_spaceship["js/modules/spaceship/spaceship.js"] --> N162_services["js/modules/spaceship/systems/services.js"]
  N159_spaceship["js/modules/spaceship/spaceship.js"] --> N157_visualEffects["js/modules/spaceship/effects/visualEffects.js"]
  N159_spaceship["js/modules/spaceship/spaceship.js"] --> N160_healthSync["js/modules/spaceship/sync/healthSync.js"]
  N166_blackjackGame["js/modules/ui/blackjackGame.js"] --> N271_mobileDetector["js/utils/mobileDetector.js"]
  N166_blackjackGame["js/modules/ui/blackjackGame.js"] --> N173_gameView["js/modules/ui/components/blackjack/gameView.js"]
  N166_blackjackGame["js/modules/ui/blackjackGame.js"] --> N170_cardDeck["js/modules/ui/components/blackjack/cardDeck.js"]
  N166_blackjackGame["js/modules/ui/blackjackGame.js"] --> N172_gameLogic["js/modules/ui/components/blackjack/gameLogic.js"]
  N166_blackjackGame["js/modules/ui/blackjackGame.js"] --> N168_animations["js/modules/ui/components/blackjack/animations.js"]
  N166_blackjackGame["js/modules/ui/blackjackGame.js"] --> N169_betting["js/modules/ui/components/blackjack/betting.js"]
  N166_blackjackGame["js/modules/ui/blackjackGame.js"] --> N171_eventHandlers["js/modules/ui/components/blackjack/eventHandlers.js"]
  N167_combatDisplay["js/modules/ui/combatDisplay.js"] --> N180_styles["js/modules/ui/components/combat/styles.js"]
  N167_combatDisplay["js/modules/ui/combatDisplay.js"] --> N179_indicators["js/modules/ui/components/combat/indicators.js"]
  N167_combatDisplay["js/modules/ui/combatDisplay.js"] --> N176_enemyDisplay["js/modules/ui/components/combat/enemyDisplay.js"]
  N167_combatDisplay["js/modules/ui/combatDisplay.js"] --> N181_weaponDisplay["js/modules/ui/components/combat/weaponDisplay.js"]
  N167_combatDisplay["js/modules/ui/combatDisplay.js"] --> N175_animations["js/modules/ui/components/combat/animations.js"]
  N167_combatDisplay["js/modules/ui/combatDisplay.js"] --> N177_eventHandlers["js/modules/ui/components/combat/eventHandlers.js"]
  N167_combatDisplay["js/modules/ui/combatDisplay.js"] --> N178_helpers["js/modules/ui/components/combat/helpers.js"]
  N173_gameView["js/modules/ui/components/blackjack/gameView.js"] --> N174_styles["js/modules/ui/components/blackjack/styles.js"]
  N189_displays["js/modules/ui/components/hud/displays.js"] --> N195_styles["js/modules/ui/components/hud/styles.js"]
  N190_eventHandlers["js/modules/ui/components/hud/eventHandlers.js"] --> N195_styles["js/modules/ui/components/hud/styles.js"]
  N192_minimap["js/modules/ui/components/hud/minimap.js"] --> N195_styles["js/modules/ui/components/hud/styles.js"]
  N193_notifications["js/modules/ui/components/hud/notifications.js"] --> N195_styles["js/modules/ui/components/hud/styles.js"]
  N194_statusIndicators["js/modules/ui/components/hud/statusIndicators.js"] --> N195_styles["js/modules/ui/components/hud/styles.js"]
  N214_terminalView["js/modules/ui/components/stargate/terminalView.js"] --> N212_screen["js/modules/ui/components/stargate/terminal/display/screen.js"]
  N214_terminalView["js/modules/ui/components/stargate/terminalView.js"] --> N211_effects["js/modules/ui/components/stargate/terminal/display/effects.js"]
  N214_terminalView["js/modules/ui/components/stargate/terminalView.js"] --> N208_parser["js/modules/ui/components/stargate/terminal/commands/parser.js"]
  N214_terminalView["js/modules/ui/components/stargate/terminalView.js"] --> N207_handlers["js/modules/ui/components/stargate/terminal/commands/handlers.js"]
  N214_terminalView["js/modules/ui/components/stargate/terminalView.js"] --> N210_messages["js/modules/ui/components/stargate/terminal/content/messages.js"]
  N214_terminalView["js/modules/ui/components/stargate/terminalView.js"] --> N209_ascii["js/modules/ui/components/stargate/terminal/content/ascii.js"]
  N214_terminalView["js/modules/ui/components/stargate/terminalView.js"] --> N213_keyboard["js/modules/ui/components/stargate/terminal/input/keyboard.js"]
  N218_customSystemCreator["js/modules/ui/customSystemCreator.js"] --> N233_apiClient["js/modules/utils/apiClient.js"]
  N218_customSystemCreator["js/modules/ui/customSystemCreator.js"] --> N186_styles["js/modules/ui/components/customSystem/styles.js"]
  N218_customSystemCreator["js/modules/ui/customSystemCreator.js"] --> N188_validation["js/modules/ui/components/customSystem/validation.js"]
  N218_customSystemCreator["js/modules/ui/customSystemCreator.js"] --> N187_systemData["js/modules/ui/components/customSystem/systemData.js"]
  N218_customSystemCreator["js/modules/ui/customSystemCreator.js"] --> N183_formView["js/modules/ui/components/customSystem/formView.js"]
  N218_customSystemCreator["js/modules/ui/customSystemCreator.js"] --> N185_preview["js/modules/ui/components/customSystem/preview.js"]
  N218_customSystemCreator["js/modules/ui/customSystemCreator.js"] --> N182_eventHandlers["js/modules/ui/components/customSystem/eventHandlers.js"]
  N218_customSystemCreator["js/modules/ui/customSystemCreator.js"] --> N184_helpers["js/modules/ui/components/customSystem/helpers.js"]
  N219_gameOverScreen["js/modules/ui/gameOverScreen.js"] --> N272_pathUtils["js/utils/pathUtils.js"]
  N220_hud["js/modules/ui/hud.js"] --> N195_styles["js/modules/ui/components/hud/styles.js"]
  N220_hud["js/modules/ui/hud.js"] --> N189_displays["js/modules/ui/components/hud/displays.js"]
  N220_hud["js/modules/ui/hud.js"] --> N193_notifications["js/modules/ui/components/hud/notifications.js"]
  N220_hud["js/modules/ui/hud.js"] --> N192_minimap["js/modules/ui/components/hud/minimap.js"]
  N220_hud["js/modules/ui/hud.js"] --> N194_statusIndicators["js/modules/ui/components/hud/statusIndicators.js"]
  N220_hud["js/modules/ui/hud.js"] --> N190_eventHandlers["js/modules/ui/components/hud/eventHandlers.js"]
  N220_hud["js/modules/ui/hud.js"] --> N191_helpers["js/modules/ui/components/hud/helpers.js"]
  N223_settings["js/modules/ui/settings.js"] --> N271_mobileDetector["js/utils/mobileDetector.js"]
  N223_settings["js/modules/ui/settings.js"] --> N202_styles["js/modules/ui/components/settings/styles.js"]
  N223_settings["js/modules/ui/settings.js"] --> N196_audioSettings["js/modules/ui/components/settings/audioSettings.js"]
  N223_settings["js/modules/ui/settings.js"] --> N198_graphicsSettings["js/modules/ui/components/settings/graphicsSettings.js"]
  N223_settings["js/modules/ui/settings.js"] --> N201_settingsView["js/modules/ui/components/settings/settingsView.js"]
  N223_settings["js/modules/ui/settings.js"] --> N200_persistence["js/modules/ui/components/settings/persistence.js"]
  N223_settings["js/modules/ui/settings.js"] --> N197_eventHandlers["js/modules/ui/components/settings/eventHandlers.js"]
  N223_settings["js/modules/ui/settings.js"] --> N199_helpers["js/modules/ui/components/settings/helpers.js"]
  N224_stargateInterface["js/modules/ui/stargateInterface.js"] --> N271_mobileDetector["js/utils/mobileDetector.js"]
  N224_stargateInterface["js/modules/ui/stargateInterface.js"] --> N214_terminalView["js/modules/ui/components/stargate/terminalView.js"]
  N224_stargateInterface["js/modules/ui/stargateInterface.js"] --> N206_systemsView["js/modules/ui/components/stargate/systemsView.js"]
  N224_stargateInterface["js/modules/ui/stargateInterface.js"] --> N215_tradingView["js/modules/ui/components/stargate/tradingView.js"]
  N224_stargateInterface["js/modules/ui/stargateInterface.js"] --> N216_upgrades["js/modules/ui/components/stargate/upgrades.js"]
  N224_stargateInterface["js/modules/ui/stargateInterface.js"] --> N205_missions["js/modules/ui/components/stargate/missions.js"]
  N224_stargateInterface["js/modules/ui/stargateInterface.js"] --> N203_eventHandlers["js/modules/ui/components/stargate/eventHandlers.js"]
  N224_stargateInterface["js/modules/ui/stargateInterface.js"] --> N204_helpers["js/modules/ui/components/stargate/helpers.js"]
  N229_starMap["js/modules/ui/starMap.js"] --> N271_mobileDetector["js/utils/mobileDetector.js"]
  N229_starMap["js/modules/ui/starMap.js"] --> N225_canvasRenderer["js/modules/ui/starmap/canvasRenderer.js"]
  N229_starMap["js/modules/ui/starMap.js"] --> N227_navigationLogic["js/modules/ui/starmap/navigationLogic.js"]
  N229_starMap["js/modules/ui/starMap.js"] --> N226_dataManager["js/modules/ui/starmap/dataManager.js"]
  N229_starMap["js/modules/ui/starMap.js"] --> N228_uiCreator["js/modules/ui/starmap/uiCreator.js"]
  N232_ui["js/modules/ui.js"] --> N220_hud["js/modules/ui/hud.js"]
  N232_ui["js/modules/ui.js"] --> N222_mobileHUD["js/modules/ui/mobileHUD.js"]
  N232_ui["js/modules/ui.js"] --> N221_miningDisplay["js/modules/ui/miningDisplay.js"]
  N232_ui["js/modules/ui.js"] --> N231_targetingUI["js/modules/ui/targetingUI.js"]
  N232_ui["js/modules/ui.js"] --> N224_stargateInterface["js/modules/ui/stargateInterface.js"]
  N232_ui["js/modules/ui.js"] --> N219_gameOverScreen["js/modules/ui/gameOverScreen.js"]
  N232_ui["js/modules/ui.js"] --> N217_controlsMenu["js/modules/ui/controlsMenu.js"]
  N232_ui["js/modules/ui.js"] --> N229_starMap["js/modules/ui/starMap.js"]
  N232_ui["js/modules/ui.js"] --> N166_blackjackGame["js/modules/ui/blackjackGame.js"]
  N232_ui["js/modules/ui.js"] --> N223_settings["js/modules/ui/settings.js"]
  N232_ui["js/modules/ui.js"] --> N230_startScreen["js/modules/ui/startScreen.js"]
  N232_ui["js/modules/ui.js"] --> N270_memoryManager["js/utils/memoryManager.js"]
  N232_ui["js/modules/ui.js"] --> N271_mobileDetector["js/utils/mobileDetector.js"]
  N234_combatSystem["js/systems/combat/combatSystem.js"] --> N22_system["js/core/system.js"]
  N234_combatSystem["js/systems/combat/combatSystem.js"] --> N1_healthComponent["js/components/combat/healthComponent.js"]
  N234_combatSystem["js/systems/combat/combatSystem.js"] --> N12_transform["js/components/transform.js"]
  N234_combatSystem["js/systems/combat/combatSystem.js"] --> N3_rigidbody["js/components/physics/rigidbody.js"]
  N234_combatSystem["js/systems/combat/combatSystem.js"] --> N4_mesh["js/components/rendering/mesh.js"]
  N234_combatSystem["js/systems/combat/combatSystem.js"] --> N270_memoryManager["js/utils/memoryManager.js"]
  N235_separationBehavior["js/systems/combat/enemy/behaviors/separationBehavior.js"] --> N12_transform["js/components/transform.js"]
  N235_separationBehavior["js/systems/combat/enemy/behaviors/separationBehavior.js"] --> N3_rigidbody["js/components/physics/rigidbody.js"]
  N235_separationBehavior["js/systems/combat/enemy/behaviors/separationBehavior.js"] --> N0_enemyAI["js/components/combat/enemyAI.js"]
  N240_enemyLifecycle["js/systems/combat/enemyLifecycle.js"] --> N12_transform["js/components/transform.js"]
  N240_enemyLifecycle["js/systems/combat/enemyLifecycle.js"] --> N0_enemyAI["js/components/combat/enemyAI.js"]
  N240_enemyLifecycle["js/systems/combat/enemyLifecycle.js"] --> N1_healthComponent["js/components/combat/healthComponent.js"]
  N240_enemyLifecycle["js/systems/combat/enemyLifecycle.js"] --> N4_mesh["js/components/rendering/mesh.js"]
  N240_enemyLifecycle["js/systems/combat/enemyLifecycle.js"] --> N3_rigidbody["js/components/physics/rigidbody.js"]
  N241_enemyPoolManager["js/systems/combat/enemyPoolManager.js"] --> N12_transform["js/components/transform.js"]
  N241_enemyPoolManager["js/systems/combat/enemyPoolManager.js"] --> N0_enemyAI["js/components/combat/enemyAI.js"]
  N241_enemyPoolManager["js/systems/combat/enemyPoolManager.js"] --> N1_healthComponent["js/components/combat/healthComponent.js"]
  N241_enemyPoolManager["js/systems/combat/enemyPoolManager.js"] --> N4_mesh["js/components/rendering/mesh.js"]
  N241_enemyPoolManager["js/systems/combat/enemyPoolManager.js"] --> N3_rigidbody["js/components/physics/rigidbody.js"]
  N241_enemyPoolManager["js/systems/combat/enemyPoolManager.js"] --> N5_trail["js/components/rendering/trail.js"]
  N243_enemySystem["js/systems/combat/enemySystem.js"] --> N22_system["js/core/system.js"]
  N243_enemySystem["js/systems/combat/enemySystem.js"] --> N5_trail["js/components/rendering/trail.js"]
  N243_enemySystem["js/systems/combat/enemySystem.js"] --> N4_mesh["js/components/rendering/mesh.js"]
  N243_enemySystem["js/systems/combat/enemySystem.js"] --> N241_enemyPoolManager["js/systems/combat/enemyPoolManager.js"]
  N243_enemySystem["js/systems/combat/enemySystem.js"] --> N242_enemySpawner["js/systems/combat/enemySpawner.js"]
  N243_enemySystem["js/systems/combat/enemySystem.js"] --> N240_enemyLifecycle["js/systems/combat/enemyLifecycle.js"]
  N243_enemySystem["js/systems/combat/enemySystem.js"] --> N235_separationBehavior["js/systems/combat/enemy/behaviors/separationBehavior.js"]
  N243_enemySystem["js/systems/combat/enemySystem.js"] --> N236_difficultyScaling["js/systems/combat/enemy/state/difficultyScaling.js"]
  N243_enemySystem["js/systems/combat/enemySystem.js"] --> N237_dockingManager["js/systems/combat/enemy/state/dockingManager.js"]
  N243_enemySystem["js/systems/combat/enemySystem.js"] --> N239_spawnMonitoring["js/systems/combat/enemy/updates/spawnMonitoring.js"]
  N244_enemySpawner["js/systems/combat/spawner/enemySpawner.js"] --> N252_progression["js/systems/combat/spawner/waves/progression.js"]
  N244_enemySpawner["js/systems/combat/spawner/enemySpawner.js"] --> N248_builder["js/systems/combat/spawner/formations/builder.js"]
  N244_enemySpawner["js/systems/combat/spawner/enemySpawner.js"] --> N250_scheduler["js/systems/combat/spawner/timing/scheduler.js"]
  N244_enemySpawner["js/systems/combat/spawner/enemySpawner.js"] --> N247_enemyFactory["js/systems/combat/spawner/factory/enemyFactory.js"]
  N245_meshGeneration["js/systems/combat/spawner/factory/enemies/meshGeneration.js"] --> N4_mesh["js/components/rendering/mesh.js"]
  N245_meshGeneration["js/systems/combat/spawner/factory/enemies/meshGeneration.js"] --> N251_definitions["js/systems/combat/spawner/waves/definitions.js"]
  N246_spectralDrone["js/systems/combat/spawner/factory/enemies/spectralDrone.js"] --> N12_transform["js/components/transform.js"]
  N246_spectralDrone["js/systems/combat/spawner/factory/enemies/spectralDrone.js"] --> N1_healthComponent["js/components/combat/healthComponent.js"]
  N246_spectralDrone["js/systems/combat/spawner/factory/enemies/spectralDrone.js"] --> N0_enemyAI["js/components/combat/enemyAI.js"]
  N246_spectralDrone["js/systems/combat/spawner/factory/enemies/spectralDrone.js"] --> N4_mesh["js/components/rendering/mesh.js"]
  N246_spectralDrone["js/systems/combat/spawner/factory/enemies/spectralDrone.js"] --> N3_rigidbody["js/components/physics/rigidbody.js"]
  N246_spectralDrone["js/systems/combat/spawner/factory/enemies/spectralDrone.js"] --> N251_definitions["js/systems/combat/spawner/waves/definitions.js"]
  N247_enemyFactory["js/systems/combat/spawner/factory/enemyFactory.js"] --> N246_spectralDrone["js/systems/combat/spawner/factory/enemies/spectralDrone.js"]
  N247_enemyFactory["js/systems/combat/spawner/factory/enemyFactory.js"] --> N245_meshGeneration["js/systems/combat/spawner/factory/enemies/meshGeneration.js"]
  N247_enemyFactory["js/systems/combat/spawner/factory/enemyFactory.js"] --> N251_definitions["js/systems/combat/spawner/waves/definitions.js"]
  N248_builder["js/systems/combat/spawner/formations/builder.js"] --> N12_transform["js/components/transform.js"]
  N248_builder["js/systems/combat/spawner/formations/builder.js"] --> N249_patterns["js/systems/combat/spawner/formations/patterns.js"]
  N252_progression["js/systems/combat/spawner/waves/progression.js"] --> N251_definitions["js/systems/combat/spawner/waves/definitions.js"]
  N253_deploymentSystem["js/systems/deployables/deploymentSystem.js"] --> N22_system["js/core/system.js"]
  N254_dockingSystem["js/systems/docking/dockingSystem.js"] --> N22_system["js/core/system.js"]
  N255_explosionHandler["js/systems/effects/explosionHandler.js"] --> N22_system["js/core/system.js"]
  N256_healthSystem["js/systems/entity/healthSystem.js"] --> N22_system["js/core/system.js"]
  N261_miningSystem["js/systems/mining/miningSystem.js"] --> N22_system["js/core/system.js"]
  N261_miningSystem["js/systems/mining/miningSystem.js"] --> N257_beamMechanics["js/systems/mining/core/beamMechanics.js"]
  N261_miningSystem["js/systems/mining/miningSystem.js"] --> N260_targetTracking["js/systems/mining/core/targetTracking.js"]
  N261_miningSystem["js/systems/mining/miningSystem.js"] --> N258_resourceCollection["js/systems/mining/core/resourceCollection.js"]
  N261_miningSystem["js/systems/mining/miningSystem.js"] --> N259_stateManagement["js/systems/mining/core/stateManagement.js"]
  N262_collisionSystem["js/systems/physics/collisionSystem.js"] --> N22_system["js/core/system.js"]
  N262_collisionSystem["js/systems/physics/collisionSystem.js"] --> N270_memoryManager["js/utils/memoryManager.js"]
  N263_movementSystem["js/systems/physics/movementSystem.js"] --> N22_system["js/core/system.js"]
  N264_InstancedRenderer["js/systems/rendering/InstancedRenderer.js"] --> N22_system["js/core/system.js"]
  N265_renderSystem["js/systems/rendering/renderSystem.js"] --> N22_system["js/core/system.js"]
  N266_trailSystem["js/systems/rendering/trailSystem.js"] --> N22_system["js/core/system.js"]
  N267_visualEffectsSystem["js/systems/rendering/visualEffectsSystem.js"] --> N22_system["js/core/system.js"]
  N268_tradingSystem["js/systems/trading/tradingSystem.js"] --> N22_system["js/core/system.js"]
  N269_deployableLaserSystem["js/systems/weapons/deployableLaserSystem.js"] --> N22_system["js/core/system.js"]
  N273_main["src/main.js"] --> N274_three_imports["src/three-imports.js"]
  N273_main["src/main.js"] --> N137_PoolRegistry["js/modules/pooling/PoolRegistry.js"]